dist: trusty

language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - BROADWAY_VERSION=^1.0
  - BROADWAY_VERSION=^2.0

matrix:
  exclude:
    - php: 5.5
      env: BROADWAY_VERSION=^2.0
    - php: 5.6
      env: BROADWAY_VERSION=^2.0
  allow_failures:
    - php: hhvm

before_install:
  - composer require "broadway/broadway:${BROADWAY_VERSION}"

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar

script:
  - vendor/bin/phpunit --config=phpunit-coverage.xml --coverage-clover=coverage.xml

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
